
    extends: [eslint:recommended, plugin:node/recommended, plugin:react/recommended]
    plugins: [node, react]
    # parserOptions:
    env:
        browser: true
        node: true
        es6: true
        # ecmaVersion: 2016
    
    # globals: 
    
    rules: 
        semi: "error"
        arrow-body-style: "error"
        arrow-parens: "error"
        arrow-spacing: "error"
        generator-star-spacing: "error"
        no-duplicate-imports: "error"
        no-useless-computed-key: "error"
        no-useless-constructor: "error"
        no-useless-rename: "error"
        no-var: "error"
        object-shorthand: "error"
        prefer-arrow-callback: "error"
        prefer-const: "error"
        prefer-rest-params: "error"
        prefer-spread: "error"
        prefer-template: "error"
        rest-spread-spacing: "error"
        template-curly-spacing: "error"
        yield-star-spacing: "error"
        node/no-unsupported-features: ["error", version: 6]
    
    settings: 
        # react: 
        #   createClass: "createReactClass" # Regex for Component Factory to use default to createReactClass
        #   pragma: "React"   # Pragma to use default to React
        #   version: "detect" # React version. detect automatically picks the version you have installed.
        #                     # You can also use `16.0` `16.3` etc if you want to override the detected value.
        #   flowVersion: 0.53 # Flow version
        
        propWrapperFunctions: [
            # The names of any function used to wrap propTypes e.g. `forbidExtraProps`. If this isn't set any propTypes wrapped in a function will be skipped.
            # forbidExtraProps
            property: freeze,
            object: Object,
            property: myFavoriteWrapper
        ]
      

