[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
    autocmd BufRead, BufNewFile *.mkd set filetype=markdown
    autocmd BufRead, BufNewFile *.mk set filetype=markdown
    let g:vim_markdown_folding_disabled=1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']
hook_add = '''
    nnoremap <silent><C-p> : PrevimOpen<CR>
    let g:previm_open_cmd = 'open -a Safari'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['kannokanno/previm']
hook_add = '''
	let g:netrw_nogx = 1 " disable netrw's gx mapping.
	nmap gx <Plug>(openbrowser-smart-search)
	vmap gx <Plug>(openbrowser-smart-search)
'''


[[plugins]]
repo = 'vim-scripts/dbext.vim'
on_ft = ['sql']
hook_add = '''
	let dbext_default_type="PGSQL"
	let g:dbext_default_profile_postgres = 'type=PGSQL:host=127.0.0.1:user=postgres:dbname=cookpad:passwd=Kento012:port=5432'
	let g:dbext_default_profile = 'postgres'
'''

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = ['ejs']
hook_add = '''
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
	let g:typescript_indent_disable = 1
'''

[[plugins]]
repo = 'Quramy/vim-js-pretty-template'
on_ft = ['javascript', 'typescript']
hook_add = '''
	autocmd FileType javascript JsPreTmpl
	autocmd FileType typescript JsPreTmpl
	autocmd FileType javascript.jsx JsPreTmpl
'''

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']
hook_add = '''
'''

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
hook_add = '''
'''
 
[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = 'nnoremap <silent><Space>vs :VimShellPop<CR>'
on_map = ['<Leader>vs']

[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = ['Vinarise']


[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_map = ['<Space>tm']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'lvht/phpcd.vim'
on_ft = ['php']
hook_add = '''
	let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
	let g:deoplete#ignore_sources.php = ['omni']
'''

[[plugins]]
repo = 'severin-lemaignan/vim-minimap'
on_map = ['<Leader>mm']
