[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
  " Setup used libraries
  let g:used_javascript_libs = 'jquery,react,d3'
  let b:javascript_lib_use_jquery = 1
  let b:javascript_lib_use_react = 1
  let b:javascript_lib_use_d3 = 1
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescript.react', 'typescriptreact']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['typescript', 'javascript', 'typescript.react', 'typescriptreact']


[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
    autocmd BufRead, BufNewFile *.mkd set filetype=markdown
    autocmd BufRead, BufNewFile *.mk set filetype=markdown
    let g:vim_markdown_folding_disabled=1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']
hook_add = '''
    nnoremap <silent><C-p> : PrevimOpen<CR>
    let g:previm_open_cmd = 'open -a Safari'
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['kannokanno/previm']
hook_add = '''
	let g:netrw_nogx = 1 " disable netrw's gx mapping.
	nmap gx <Plug>(openbrowser-smart-search)
	vmap gx <Plug>(openbrowser-smart-search)
'''


[[plugins]]
repo = 'vim-scripts/dbext.vim'
on_ft = ['sql']
hook_add = '''
	let dbext_default_type="PGSQL"
	let g:dbext_default_profile_postgres = 'type=PGSQL:host=127.0.0.1:user=postgres:dbname=cookpad:passwd=Kento012:port=5432'
	let g:dbext_default_profile = 'postgres'
'''

[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = ['ejs']
hook_add = '''
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.react', 'typescriptreact']
hook_add = '''
	let g:typescript_indent_disable = 1
'''

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'typescript.react', 'typescriptreact']
hook_add = '''
	" dark red
	hi tsxTagName guifg=#E06C75
	" orange
	hi tsxCloseString guifg=#F99575
	hi tsxCloseTag guifg=#F99575
	hi tsxAttributeBraces guifg=#F99575
	hi tsxEqual guifg=#F99575
	" yellow
	hi tsxAttrib guifg=#F8BD7F cterm=italic
'''

[[plugins]]
repo = 'Quramy/vim-js-pretty-template'
on_ft = ['javascript', 'typescript']
hook_add = '''
	autocmd FileType javascript JsPreTmpl
	autocmd FileType typescript JsPreTmpl
	autocmd FileType javascript.jsx JsPreTmpl
'''

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'typescriptreact']
hook_add = '''
'''

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
hook_add = '''
'''
 
[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = 'nnoremap <silent><Space>vs :VimShellPop<CR>'
on_map = ['<Leader>vs']

[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = ['Vinarise']


[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_map = ['<Space>tm']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']
